throne/urls.py
from django.conf.urls import url
from django.contrib import admin
from crud.service import throne
from app02 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crud/', throne.site.urls),
    url(r'^hosts/', views.hosts),
    url(r'^add/', views.add),
    url(r'^editor/(\d+)/', views.editor),
]

app01/models.py
from django.db import models

class UserInfo(models.Model):

    name=models.CharField(verbose_name="用户名",max_length=32)
    pwd=models.CharField(verbose_name="密码",max_length=32)

    def __str__(self):
        return self.name

class Host(models.Model):
    ip=models.GenericIPAddressField(verbose_name="ip")
    port=models.IntegerField(verbose_name="端口")
    user=models.ForeignKey(to=UserInfo,verbose_name="用户")

    def __str__(self):
        return self.user.name

app02/models.py
from django.db import models

class Student(models.Model):
    name=models.CharField(verbose_name="姓名",max_length=32)
    gender_choice=((1,"男"),(2,"女"))
    gender=models.IntegerField(verbose_name="性别",choices=gender_choice)
    age=models.IntegerField(verbose_name="年龄")

app03/models.py
from django.db import models

from django.db import models

class Role(models.Model):
    title = models.CharField(verbose_name='角色标题',max_length=32)

    def __str__(self):
        return self.title

class Department(models.Model):
    caption = models.CharField(verbose_name='部门名称',max_length=23)
    def __str__(self):
        return self.caption


class UserInfo(models.Model):
    name = models.CharField(verbose_name='姓名',max_length=32)
    email = models.CharField(verbose_name='邮箱',max_length=32)
    gender_choices = (
        (1,'男'),
        (2,'女'),
        (3,'少伟'),
    )
    gender = models.IntegerField(verbose_name='性别',choices=gender_choices)
    depart = models.ForeignKey(verbose_name="部门",to=Department)
    roles = models.ManyToManyField(verbose_name="角色", to=Role)

crud/models.py
from django.db import models

# Create your models here.

app02/views.py
from django.shortcuts import render,redirect
from app02.utils.pager import Pagination
from app02 import models
from django.forms import ModelForm
from django.http import QueryDict
class StrudentForm(ModelForm):
    class Meta:
        model=models.Student
        fields="__all__"

def hosts(request):

    # page_num=int(request.GET.get("page",1))
    # show_count=10
    #
    # page_max,div=divmod(len(data_list),show_count)
    # if div:
    #     page_max+=1
    #
    # #每页显示的数据
    # page_list=[]  #页码
    # for i in range(1,page_max+1):
    #     if i == page_num:
    #         page_list.append('<a class="active" href="/hosts/?page=%s">%s</a>' % (i, i))
    #     else:
    #         page_list.append('<a href="/hosts/?page=%s">%s</a>'%(i,i))
    # pagelist=''.join(page_list)
    #
    # show_data_list=data_list[show_count*(page_num-1):page_num*show_count]


    data_list = models.Student.objects.all()
    pager_obj = Pagination(request.GET.get('page', 1), len(data_list), request.path_info, request.GET)
    student_list = data_list[pager_obj.start:pager_obj.end]
    html = pager_obj.page_html()


    params=QueryDict(mutable=True)
    params["_filter_list"]=request.GET.urlencode()
    condition=params.urlencode()
    return render(request,"hosts.html",{"student_list":student_list,"pagelist":html,"condition":condition})


def add(request):
    if request.method=="GET":
        form =StrudentForm()
    else:
        condition=request.GET.get("_filter_list")
        form=StrudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/hosts/?%s"%condition)
    return render(request, "add.html", {"form": form})

def editor(request,nid):
    student = models.Student.objects.filter(id=nid).first()
    if request.method=="GET":
        form=StrudentForm(instance=student)

    else:
        form=StrudentForm(data=request.POST,instance=student)
        if form.is_valid():
            form.save()
            return redirect('/hosts/?%s'%request.GET.get("_filter_list"))
    return render(request, "editor.html", {"form": form})

app03/views.py
from django.shortcuts import render

# Create your views here.

crud/templates/crud/add.html
{% load staticfiles %}
{% load change_form %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "bootstrap-3.3.7-dist/css/bootstrap.min.css"  %}">
    <link rel="stylesheet" href="{% static "mycss/form-input.css" %}">
</head>
<body>
<div class="container">
    <h2>添加页面</h2>
    {% form form %}
</div>



</body>
</html>

crud/templates/crud/change.html
{% load staticfiles %}
{% load change_form %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "bootstrap-3.3.7-dist/css/bootstrap.min.css"  %}">
    <link rel="stylesheet" href="{% static "mycss/form-input.css" %}">
</head>
<body>
<div class="container">
    <h2>修改页面</h2>
    {% form form %}
</div>

</body>
</html>

crud/templates/crud/changelist.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <style>
        .list_filter a{display:inline-block; padding: 5px 10px;margin: 5px 5px  ;border: 1px solid #1b6d85}
        .list_filter a.active{background-color: #2e6da4;color: white}
        .list_filter .verbose_name{
                            line-height: 42px;
                            float: left;
                            text-align: right;
                            font-size: 16px;
                            font-weight: 500;}
    </style>
</head>
<body>
<div class="container">
    <h2>列表页面</h2>

    {% if obj.show_add_btn %}
        <div class="pull-right">
            <a class="btn btn-default" href="{{ obj.add_url}}?{{ obj.condition }}">添加</a>
        </div>
        <hr>
    {% endif %}
<div class="list_filter">
    {% for filter_row_obj in obj.gen_comb_filter %}
        <div>
        {% for foo in filter_row_obj %}
                {{ foo }}
        {% endfor %}
        </div>
{% endfor %}
</div>

    {% if obj.show_search %}
    <form>
        <div class="form-group">
            <input class="form-control" name="{{ obj.search_key }}" value="{{ obj.condition_key }}" type="text" placeholder="请输入搜索条件" style="display: inline-block;width: 200px">
            <button class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
        </div>
    </form>
    {% endif %}
<form method="post">
    {% if obj.show_actions %}
        {% csrf_token %}
        <div class="form-group">
        <select name="action"  class="form-control" style="display: inline-block;width: 200px">
            <option value="" >--------------</option>
            {% for foo in obj.mudify_actions %}
                <option value="{{ foo.name }}" >{{ foo.text }}</option>
            {% endfor %}
        </select>
        <button class="btn btn-primary">执行</button>
        </div>
    {% endif %}

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            {% for head in obj.get_header %}
            <th>{{ head }}</th>
            {% endfor %}

        </tr>
        </thead>

        <tbody class="tbody">
        {% for data in obj.get_data_list %}
            <tr>
            {% for field in data %}
            <td>{{ field }}</td>
            {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</form>
<div class="pull-right">
    <ul class="pagination">
        {{ obj.page_html|safe }}
    </ul>
</div>

</div>

<script src="{% static "jquery-3.2.1.min.js" %}"></script>
<script>
    $("#select_all").click(function () {
        var checkbox=$(".tbody input[type='checkbox']");
        if (checkbox.attr("checked")){
             checkbox.removeAttr("checked")
        }
        else{
            checkbox.attr("checked","checked")

        }

    })
</script>
</body>
</html>

crud/templates/crud/form.html
<hr>
<form method="post" class="form-horizontal" novalidate>
        {% csrf_token %}
        {% for dic in form %}
            <div class="col-sm-5">
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ dic.item.label }}</label>
                    <div class="col-sm-10">

                        {% if dic.is_popup %}
                            <div class="row">
                            <div class="col-sm-6">
                               {{ dic.item }}
                            </div>
                            <div class="col-sm-3">
                                <a onclick="popUp('{{ dic.popurl }}')"><span class="glyphicon glyphicon-plus">添加</span></a>
                            </div>

                            </div>
                        {% else %}
                            {{ dic.item }}
                        {% endif %}
                        {{ dic.item.errors }}
                    </div>
                </div>
            </div>

        {% endfor %}
        <div class="col-sm-1 col-sm-offset-9">
            <input class="btn btn-primary" type="submit" value="提交">
        </div>
    </form>

<script>

    function popupCallback(dic) {
        var option = document.createElement('option');
        option.value = dic.id;
        option.text = dic.text;
        option.setAttribute('selected','selected');
        document.getElementById(dic.popbackid).appendChild(option);
    }

    function popUp(url) {
        console.log(url);
        var popupPage = window.open(url, url, "status=1, height:500, width:600, toolbar=0, resizeable=0");
    }

</script>

crud/templates/crud/pop_response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>正在关闭</title>
</head>
<body>

<script>
    (function () {
        var dic = {{ result|safe }};
        opener.popupCallback(dic);
        window.close();
    })()
</script>

</body>
</html>

templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
<h2>添加页面</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交">
</form>

</body>
</html>

templates/editor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
<h2>修改页面</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交">
</form>

</body>
</html>

templates/hosts.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "bootstrap-3.3.7-dist/css/bootstrap.min.css" %}">
    <style>
        a{padding: 2px 6px}
        .active{background-color: #2aabd2}
    </style>
</head>
<body>
<div class="container">
<h2>学生页面</h2>
    <a class="btn btn-primary" href="/add/?{{ condition }}">添加</a>
    <a class="btn btn-primary" href="/hosts/?gender=1">男生</a>
    <a class="btn btn-primary" href="/hosts/?gender=2">女生</a>

 <table class="table table-bordered">
    <thead>
    <tr>
        <th>id</th>
        <th>姓名</th>
        <th>性别</th>
        <th>年龄</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for student in student_list %}
    <tr>
    <td>{{ student.id }}</td>
    <td>{{ student.name }}</td>
    <td>{{ student.get_gender_display}}</td>
    <td>{{ student.age }}</td>
    <td><a href="/editor/{{ student.id }}/?{{ condition }}">编辑</a></td>
    </tr>
    {% endfor %}

</table>

<ul class="pagination pull-right">
  {{ pagelist|safe }}
</ul>

</div>


</body>
</html>